unique_ids:
  assets:
    standard-page.html: DYHKH6ZH5JLJ2GELV7OMGOBNVCHYGR36
    theme.css: PB2XBFFVBNAN2JDDE2XLQUYF67RGMNFM
  forms:
    Form1: SQUYEAZSMAYIDIXILAF4EC2GYZQKFU2X
  modules: {}
  scripts: {}
  server_modules: {}
